### ISSUE TITLE
Clarification needed: Inconsistent Timezone Flag Use.

### ISSUE THREAD

**Issue by lwjoyner** [comp426-2023-spring/a02#2] opened 2023-02-01 19:43 UTC
If you can answer "TRUE" to the first two items below, then create a pull request and correct the error:

1. [ ] There is an error in the text.
2. [ ] I know how to correct the error
3. [ ] I created a pull request to correct the error. 

If you can answer "TRUE" to all of the following, then create an issue:

- [ ] I searched the issues for duplicates and related issues and didn't find any.
- [ ] I read documentation about the thing that is confusing me.
- [ ] I Googled the thing that I find confusing.

Did all of the above and still need help? Create an issue.
------------------------------------------------------------------

Make sure to add **all the information needed to understand the error** so that someone can help. If the info is missing we'll add the 'Needs more information' label and close the issue until there is enough information.

- [ ] Provide URL of the file with the confusing thing.
- [ ] Identify the line number(s) in the file where the cunfusing thing is. 
- [ ] Describe what you find confusing?
- [ ] Take a guess and describe what you think the confusing thing might mean?
- [ ] Add links to the documentation that you read to try to solve this (StackOverflow, package docs, anything)

Delete text above this line before you submit your issue. Place your issue information in the appropriate sections below. 

#### URL of file with confusing thing

https://github.com/comp426-2023-spring/a02-functions-lwjoyner/blob/main/README.md

#### Line number of confusing thing

47, 261, 262, 263

#### What is confusing?

You say earlier in the README that you want the timezone flag to be "-z", yet you use it as "-t" in the test examples. Which one is it?

#### What do you think the confusing thing means?

I believe you meant -z because of your galo.sh script using -z

#### What did you read to try to understand better what is happening and solve the issue?
I read your galo.sh code to see if -t did anything and the answer was no.

**Comment by daqichen** [comment] 2023-02-02 20:22
Yep, `-z` is what was intended within the test scripts. Will update the Readme.md and closing the issue.

For future reference, please delete the checklist to avoid convoluted information in the issue, the checklist is simply for your reference prior to escalating an error into an issue.

> Delete text above this line before you submit your issue. Place your issue information in the appropriate sections below.

**Closed as completed by daqichen** 2023-02-02 20:22 UTC
Labels: documentation
